### ISSUE TITLE
Move settings to AppData on Windows

### ISSUE THREAD

**Issue by wrooot** [Alameyo/flame#3]
Program settings should not be saved directly in a user's profile on Windows (e.g. C:\users\wroot\flame). It should go to C:\Users\wroot\AppData\Roaming\flame\.

**Comment by Alameyo** [comment]
Thanks for noting that. I definitely will move to fixing properties/files issues.

**Comment by wrooot** [comment]
This might help https://stackoverflow.com/questions/9235734/how-do-i-get-the-value-of-windows-appdata-location-variable-in-java/9235890 Although by doing that you will have to have separate code for Windows and other OSes to save settings. Spark also was saving just in home folder for all systems in the past. But now it saves to APPDATA\Spark on Windows. There is even an import code. if you upgrade from an older version.
